let Routes = require('express')
let router = new Routes()
let userController = require('../Controller/User')

router.post('/register_user', userController.addUser)
router.get('/get_all_user', userController.getAllUser)
router.get('/check_admin', userController.checkAdmin)
router.get('/login_user', userController.getUser)
router.get('/login_user_again', userController.getUserAgain)
router.put('/change_is_show', userController.changeIsShow)
router.put('/change_password', userController.changePassword)
router.put('/change_login', userController.changeLogin)
router.get('/get_position/:id', userController.getPosition)
router.get('/get_winners', userController.getWinners)
router.get('/get_info_user', userController.getInfoUser)
router.get('/check_password/:id/:name', userController.checkUserByPassword)
router.get('/get_score', userController.getScore)
router.post('/add_clicker', userController.addClicker)
router.get('/check_password', userController.checkPassword)
router.put('/fortuna_unavailable', userController.fortuneUnavailable)
router.put('/fortuna_available', userController.fortuneAvailable)
router.post('/add_victory', userController.addVictory)
router.put('/check_victory_answer', userController.checkVictory)
router.get('/get_clicker/:id', userController.getClicker)
router.get('/get_victory/:id', userController.getVictory)
router.get('/get_answer/:subject/:id', userController.getAnswer)

module.exports = router